### ISSUE TITLE
Quoting string path parameters

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [rbeauchamp/Swashbuckle.OData#146]
This was supposed to be fixed in #31 (I think) but I'm still having the issue that _string_ path parameters are not correctly quoted.

For example, the following OData function:

![odata-string-params](https://cloud.githubusercontent.com/assets/1670232/26580206/7020af3c-4537-11e7-80a0-446cb03de557.png)

Typing in the _userEmail_ and _employeeEmail_ parameters without quotes results in the following incorrect url because the parameters are not quoted:

_https://.../odata/GetEmployeeForRegistration(UserEmail=foo,EmployeeEmail=bar)_

This should be:

_https://.../odata/GetEmployeeForRegistration(UserEmail='foo',EmployeeEmail='bar')_

Entering the parameters with quotes gives the correct url:

![odata-string-params-correct](https://cloud.githubusercontent.com/assets/1670232/26580379/178ceae2-4538-11e7-869b-ac2bb3498a9c.png)

**Comment by Atvaark** [comment]
#31 does a case sensitive comparison. It doesn't find your parameters by name (*userEmail* and *UserEmail*) and thus doesn't quote them.
Same issues with functions bound to entity types. e. g. `Customers({Key})/Default.FuncName()` or even a simple get to the `Customers({Key})` resource if your method signature looks like this `public IHttpActionResult Get([FromODataUri] string key)`

Issue:
https://github.com/rbeauchamp/Swashbuckle.OData/blob/725e8aee9ca054397af578eebda36d9ad0121887/Swashbuckle.OData/Descriptions/ApiDescriptionExtensions.cs#L16

Instead of `Contains` either a `Regex` with `IgnoreCase` option or `.IndexOf(..., StringComparison.OrdinalIgnoreCase)` should be used to find all matching parameters.
The workaround is renaming your method parameters to match the URL parameters. But that would violate the C# naming conventions.
