### ISSUE TITLE
IncludeXmlComments and AddCustomSwaggerRoute

### ISSUE THREAD

**Issue by jmsvl** [rbeauchamp/Swashbuckle.OData#148]
Hi,

Is Swashbuckle.OData going to support Xml Comments external files? 

And I also cannot get any documentation on CustomSwaggerRoutes to show.

Thanks,

Jorge

**Comment by cibergarri** [comment]
Hi Jorge, actually Swashbuckle.OData support Xml Comment external files since some months ago. You can see an example of this working in the sample project: https://github.com/rbeauchamp/Swashbuckle.OData/blob/9d5fa0a74c0dea49a20c643aab428be21aa3363e/Swashbuckle.OData.Sample/App_Start/SwaggerConfig.cs
Regarding the CustomSwaggerRoutes, you have some information in the readme:
https://github.com/rbeauchamp/Swashbuckle.OData#custom-swagger-routes

Regards.
Javier.

**Comment by jmsvl** [comment]
I have tried the sample and, indeed, it works as intended. But we're using MultipleApiVersions instead of single as in the sample. 

Could this be causing the problem with our xml external file?

**Comment by jmsvl** [comment]
I think I've found the problem and opened an Issue on Swashbuckle describing it:

https://github.com/domaindrivendev/Swashbuckle/issues/1102

**Comment by jmsvl** [comment]
Can anyone help me with the issue?

You can see the print screens below running the Sample that Customers OData controller cannot get xml comments when using `config.EnableSystemDiagnosticsTracing();` (NuGet Microsoft.AspNet.WebApi.Tracing v5.2.3) on Register method of WebApiConfig.cs

![image](https://user-images.githubusercontent.com/6940508/27747296-7b134424-5dc2-11e7-88f0-16a0f64e8fb5.png)
