### ISSUE TITLE
[FromODataUri] vs standard parameter behaves differently

### ISSUE THREAD

**Issue by patrickmichalina** [rbeauchamp/Swashbuckle.OData#34]
This may be a little hard to explain but I will give it a shot.... I stumbled across this issue tonight and was totally confused as to why my EF context was not returning an entity I knew existed. It turns out, the way the Swagger-UI fields are handling the strings has some subtle differences.

These two signatures are actually returning the string differently:

```
public virtual async Task<IHttpActionResult> Put([FromODataUri] string key, [FromBody] T safetyEquipment)
{
     // magic stuff
}
``` 

```
public virtual async Task<IHttpActionResult> Put(string key, [FromBody] T safetyEquipment)
{
     // magic stuff
}
``` 

The string value that returned correctly was when using the [FromODataUri] version of the function.

**Comment by rbeauchamp** [comment]
Hmmmm. Interesting. Will investigate.

**Comment by rbeauchamp** [comment]
Hey Patrick, after researching this, it looks like an OData convention rather than a Swashbuckle.OData issue:

1. You need quotes if a param is a string.
2. If you add quotes to the string key without the [FromODataUri] attribute, then the string is passed with single quotes.
3. 2. If you add quotes to the string key WITH the [FromODataUri] attribute, then the string is passed without single quotes.

For example, see this [unit test](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData.Tests/StringKey/StringKeyTests.cs#L22). Please let me know if I'm missing something.
