### ISSUE TITLE
Problem with asserting odataActionParametersDescriptor != null

### ISSUE THREAD

**Issue by onslaughtq** [rbeauchamp/Swashbuckle.OData#86]
I am having an issue with an action bound to a collection that doesn't need to take any parameters.  In my setup, I simply specify the method as not taking any parameters, but this is causing Swashbuckle to fail in MapToODataActionParameter on line 19, where there is an assertion that ODataActionParameters is not null.

I'm not certain why I must specify ODataActionParameters for this bound action, if I'm not going to use them. In a different case, I have an unbound action which allows me to not specify the ODataActionParameters.

Am I simply missing a descriptor attribute somewhere to specify that the bound action takes no parameters?  I've been pouring over the code and documentation and not finding anything.

**Comment by rbeauchamp-lendingtree** [comment]
Hi Paul, can you please post your API method signature so I can accurately reproduce the issue? Thanks

**Comment by onslaughtq** [comment]
For my bound method, I have the following in the RecordsController:
```c#
[HttpPost]
[ODataRoute("Records/Portal.GetLatest()")]
[ResponseType(typeof(int))]
public async Task<IHttpActionResult> GetLatestAsync(ODataActionParameters parameters, CancellationToken cancellationToken)
{ ... }
```
For my unbound method, I have the following in the ServicesController:
```c#
[HttpPost]
[ODataRoute("EnforceRetentionPolicy()")]
[ResponseType(typeof(IEnumerable<RetentionEnforcementResult>))]
public async Task<IHttpActionResult> EnforceRetentionPolicyAsync()
{ ... }
```

In ODataConfig, I have the following model setup in a GetModel() method:
```c#
var builder = new ODataConventionModelBuilder();

builder.EntitySet<Record>("Records");
var getLatestRecords = builder.EntityType<Record>().Collection.Action("GetLatest");
getLatestRecords.Returns<int>();
getLatestRecords.Namespace = "Portal";

var enforceRetentionPolicy = builder.Action("EnforceRetentionPolicy");
enforceRetentionPolicy.Returns<RetentionEnforcementResult>();

return builder.GetEdmModel();
```

Let me know if you need anything else

**Comment by darrenfurr** [comment]
Did you ever find a resolution or workaround to this? I'm experiencing the same issue.

**Comment by kspbhat** [comment]
I am also experiencing the same problem. It is kind of show stopper. I have an ODATA action which accepts multipart content.In this case, I dont really need a ODataActionParameters because I get my json from the content itself. This method works fine without Swagger. If I add Swagger, then it expects me to add ODataActionParameters. If I add ODataActionParameter, then Swagger works, but method breaks. 

Any possible quick fix or work around is really appreciated. 

>  [HttpPost]
        [ODataRoute("documents({enterpriseId})/ebesng.uploadRendition()")]
        public IHttpActionResult UploadRenditionByEnterpriseId([FromODataUri] Guid enterpriseId)
        {
            _documentServicesHelper.UploadRendition(Request, enterpriseId);
            return Ok();
        }

Error Message:
500 : {"Message":"An error has occurred.","ExceptionMessage":"Assumption failed: odataActionParametersDescriptor != null","ExceptionType":"System.Diagnostics.Contracts.__ContractsRuntime+ContractException","StackTrace":" at System.Diagnostics.Contracts.__ContractsRuntime.TriggerFailure(ContractFailureKind kind, String msg, String userMessage, String conditionTxt, Exception inner)\r\n at System.Diagnostics.Contracts.__ContractsRuntime.ReportFailure(ContractFailureKind kind, String msg, String conditionTxt, Exception inner)\r\n at System.Diagnostics.Contracts.__ContractsRuntime.Assume(Boolean condition, String msg, String conditionTxt)\r\n at Swashbuckle.OData.Descriptions.MapToODataActionParameter.Map(Parameter swaggerParameter, Int32 parameterIndex, HttpActionDescriptor actionDescriptor)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.<>c__DisplayClass5_0.<GetHttpParameterDescriptor>b__0(IParameterMapper mapper)\r\n at

**Comment by weltmeyer** [comment]
Yep.. got the same problem. seems like swashbuckle.odata expects at least one parameter for an action.
EntitySet.EntityType.Action("ParametersLessAction").Returns<bool>() is not allowed?

**Comment by PavelPikat** [comment]
Having the same issue too (https://github.com/rbeauchamp/Swashbuckle.OData/issues/112)

**Comment by patrickmichalina** [comment]
Yes - this should be optional. It is a null failure in the Diagnostics Contracts.

**Comment by JesseKlaasse** [comment]
This still seems to be a problem, and it is kind of a showstopper for me, too. Any news on this?
